package it.snorcini.dev.bookmanager.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.PositiveOrZero;
import java.util.List;

/**
 * DTO returned to the caller, contains a list of Books.
 * <p>
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 * This class @extends {@link BookManagerBaseResponse} contains
 * generic response data.
 */
@Builder
@Getter
@Setter
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class BookListResponse extends PageableListResponse {

    public BookListResponse(@PositiveOrZero @NotNull final Long totalNumber,
                                 final List<DetailBookDTO> payload) {
        super(totalNumber);
        this.payload = payload;
    }

    /**
     * The list of books.
     */
    @Valid
    private List<DetailBookDTO> payload;


    /**
     * ToString method.
     *
     * @return a string item representation
     */
    @Override
    public String toString() {
        return new StringBuilder()
                .append("BookListResponse {\n")
                .append("    ").append(toIndentedString(super.toString())).append('\n')
                .append("    payload: ").append(toIndentedString(payload)).append('\n')
                .append('}').toString();
    }
}
