package it.snorcini.dev.bookmanager.dto;

import it.snorcini.dev.bookmanager.result.BookManagerResults;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.validation.constraints.NotNull;
import java.util.List;

/**
 * Generic response object returned by controller
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 * This class @extends {@link AbstractBaseDTO} to beautify toString method.
 */
@Getter
@Setter
@EqualsAndHashCode
@AllArgsConstructor
@NoArgsConstructor
public class BookManagerBaseResponse extends AbstractBaseDTO {

    /**
     * Operation result code.
     *
     * @see BookManagerResults
     */
    @NotNull
    protected Integer resultCode;
    /**
     * Description of result
     */
    protected String resultMessage;
    /**
     * Other information like validation error
     */
    protected List<String> resultInfo;


    /**
     * ToString method.
     *
     * @return a string item representation
     */
    @Override
    public String toString() {
        return new StringBuilder()
                .append("BookManagerBaseResponse {\n")
                .append("    resultCode: ").append(resultCode).append('\n')
                .append("    resultMessage: ").append(resultMessage).append('\n')
                .append("    resultInfo: ").append(resultInfo).append('\n')
                .append('}').toString();
    }
}
