package it.snorcini.dev.bookmanager.dto;

import it.snorcini.dev.bookmanager.error.BookManagerValidationErrors;
import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.validation.annotation.Validated;

import javax.validation.constraints.NotNull;

/**
 * DTO used to update Algorithm.
 * <p>
 * Methods:
 * - constructor
 * - getter and setter
 * - equals
 * are auto-generated by Lombok.
 * <p>
 * This class @extends {@link BookDTO}.
 */
@Getter
@Setter
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
@Validated
public class UpdateBookDTO extends BookDTO {

    /**
     * Contains the value of primary key identify the item on DB.
     */
    @NotNull(message = BookManagerValidationErrors.BOOK_ID_NULL)
    protected Long id;

    /**
     * ToString method.
     *
     * @return a string item representation
     */
    @Override
    public String toString() {
        return new StringBuilder()
                .append("UpdateAlgorithmDTO {\n")
                .append("    ").append(toIndentedString(super.toString())).append('\n')
                .append("    id: ").append(id).append('\n')
                .append('}').toString();
    }
}
